-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.todos
(
    id serial,
    title text NOT NULL DEFAULT 'new todo',
    completed boolean NOT NULL DEFAULT false,
    PRIMARY KEY (id)
);
END;